apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kubespace-n8n
  annotations:
    version: 'latest'
    description: "n8n is a free and open self hostable workflow automation tool"
spec:
  components:
    - name: kubespace-n8n
      type: webservice
      properties:
        image: n8nio/n8n:latest
        ports:
          - port: 5678
            expose: true
        cpu: "200m"
        memory: "256Mi"
        env:
          - name: N8N_BASIC_AUTH_ACTIVE
            value: "true"
          - name: N8N_BASIC_AUTH_USER
            value: kubespace
          - name: N8N_BASIC_AUTH_PASSWORD
            value: kubespace
      traits:
        - type: napptive-ingress         
          properties:
            name: kubespace-n8n
            port: 5678
            path: /
            rewritePath: /
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: kubespace-n8n-health
      type: health
      properties:
        probeInterval: 5