apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: "Please do not delete, you will lose all your data. davma.io-grafana storage components for production environments."
  name: grafana-storage
spec:
  components:
    - name: grafanadata
      type: pvc
      properties:
        name: pvc-grafana
        accessMode: "ReadWriteOnce"
  policies:
  - name: davmaio-pvc-app-health
    type: health
    properties:
      probeInterval: 5