apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: davmaio-dokuwiki
  annotations:
    version: 2022.07.31
    description: "DokuWiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database."
spec:
  components:
    - name: davmaio-dokuwiki
      type: webservice
      properties:
        image: bitnami/dokuwiki:latest
        ports:
          - port: 8080
            expose: true
        cpu: "200m"
        memory: "256Mi"
        env:
        - name: DOKUWIKI_USERNAME
          value: "admin"
        - name: DOKUWIKI_PASSWORD
          value: "admin"
        - name: DOKUWIKI_WIKI_NAME
          value: "DokuWiki"
      traits:
        - type: napptive-ingress         
          properties:
            name: davmaio-dokuwiki
            port: 8080
            path: /
            rewritePath: /
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: davmaio-dokuwiki-health
      type: health
      properties:
        probeInterval: 5