apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: davmaio-nextcloud-dev
  annotations:
    version: '24.0.5'
    description: "Nextcloud is the most popular on-premises content collaboration platform you can download."
spec:
  components:
  - name: davmaio-nextcloud-dev
    dependsOn:
      - postgres-nextcloud-dev
    type: webservice
    properties:
      image: nextcloud
      cpu: "1000m" 
      memory: 2048Mi
      ports:
      - port: 80
        expose: true
      env:
      # - name: NEXTCLOUD_ADMIN_USER
      #   value: davma.io
      # - name: NEXTCLOUD_ADMIN_PASSWORD
      #   value: nextcloud.davma.io
      - name: POSTGRES_HOST
        value: 'postgres-nextcloud-dev'
      # - name: POSTGRES_PORT
      #   value: '5432'
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_DB
        value: nextcloud
      - name: POSTGRES_PASSWORD
        value: Y2hhbmdldGhpcw==
    traits:
    - type: napptive-ingress         
      properties:
        name: davmaio-nextcloud
        port: 80
        path: /
  - name: postgres-nextcloud-dev
    type: webservice
    properties:
      image: postgres
      cpu: "500m" 
      memory: 1024Mi
      ports:
      - port: 5432
        expose: true
      env:
      - name: POSTGRES_DB
        value: nextcloud
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: Y2hhbmdldGhpcw==

  policies:
  - name: davmaio-nextcloud-health
    type: health
    properties:
      probeInterval: 5
      