apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: "Please do not delete, you will lose all your data. kubespace-grafana storage components for production environments."
  name: grafana-storage
spec:
  components:
    - name: grafanadata
      type: grafanadata
      properties:
        name: pvc-grafana
        accessMode: "ReadWriteOnce"