apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    version: 9.3.0
    description: "Grafana is the open source analytics & monitoring solution for every database."
  name: kubespace-grafana
spec:
  components:
    - name: kubespace-grafana
      type: webservice
      properties:
        image: grafana/grafana:latest
        ports:
          - port: 3000
            expose: true
        cpu: "500m"
        memory: "1024Mi"
      traits:
        - type: json-patch
          properties:
            operations:
            - op: add
              path: /spec/template/spec/securityContext
              value:
                runAsUser: 472
                runAsGroup: 472
                fsGroup: 472
                supplementalGroups:
                  - 0
        - type: napptive-ingress
          properties:
            name: kubespace-grafana
            port: 3000
            path: /
            rewritePath: /
        - type: scaler
          properties:
            replicas: 1
        - type: storage
          properties:
            pvc:
              - name: pvc-grafana
                accessModes:
                - ReadWriteOnce
                mountOnly: True
                mountPath: /var/lib/grafana
  policies:
    - name: grafana-health
      type: health
      properties:
        probeInterval: 5