apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: "Please do not delete, you will lose all your data. davma.io-trilium storage components for production environments."
  name: trilium-storage
spec:
  components:
    - name: triliumdata
      type: triliumdata
      properties:
        name: trilium-data
        accessMode: "ReadWriteOnce"
  policies:
  - name: davmaio-pvc-trilium-health
    type: health
    properties:
      probeInterval: 5