apiVersion: core.napptive.com/v1alpha1
kind: ApplicationMetadata
name: "Wiki.js"
version: '2.5.285'
description: Wiki.js The most powerful and extensible open source Wiki software. Make documentation a joy to write using Wiki.js's beautiful and intuitive interface!
keywords:
  - "Wiki.js"
  - "Wiki"
  - "davma.io"
license: "AGPL-3.0 license"
url: "https://js.wiki/"
doc: "https://docs.requarks.io/"
logo:
  - src: "https://d33wubrfki0l68.cloudfront.net/4f6939b6c203195133907e24da9964fa9afa4a68/3724c/assets/images/tool-icons/wikijs.png"
    type: "image/png"
    size: "500x500"
