apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: "Please do not delete, you will lose all your data. davma.io-wiki.js storage components for production environments."
  name: wikijs-storage
spec:
  components:
    - name: dbdata
      type: dbdata
      properties:
        name: db-data
        accessMode: "ReadWriteOnce"
    - name: wikijsdata
      type: wikijsdata
      properties:
        name: wikijs-data
        accessMode: "ReadWriteOnce"
    - name: wikijsconfig
      type: wikijsconfig
      properties:
        name: wikijs-config
        accessMode: "ReadWriteOnce"
  policies:
  - name: davmaio-pvc-app-health
    type: health
    properties:
      probeInterval: 5