name: DokuWiki
on:
  push:
    branches:
      - 'main'
    paths:
      - "applications/dokuwiki/napptive/trialComponent/**"
      - "applications/dokuwiki/napptive/componentPROD/**"
      - "applications/dokuwiki/napptive/componentPVC/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          # - base: 'latest'
          #   tag: 'prod'
          # - base: 'storage'
          #   tag: 'pvc'
    steps:
      - uses: actions/checkout@v2
      - uses: napptive-actions/catalog-push-action@v5.0.0
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./applications/dokuwiki/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "DokuWiki"
          tag: "${{ matrix.base }}"