name: Update Grafana in to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "grafana/napptive/trialComponent/**"
      - "grafana/napptive/componentPROD/**"
      - "grafana/napptive/componentPVC/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          - base: 'latest'
            tag: 'prod'
          - base: 'storage'
            tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v4.2.0
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./grafana/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Grafana"
          tag: "${{ matrix.base }}"