name: image-jupyterTF-dbConn
on:
  push:
    branches:
      - 'main'
      # - 'packages'
    paths:
      - "images/jupyter/tensorflow-dbConnectors/**"
      - "!images/jupyter/tensorflow-dbConnectors/README.md"
      - "!build.rb"
  schedule:
    - cron: "0 0 * * 0-6"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: jupyter/tensorflow-notebook:python-3.10.4
            tag: '3.10'
          - base: jupyter/tensorflow-notebook:python-3.11.4
            tag: '3.11'
          - base: jupyter/tensorflow-notebook:python-3.11.4
            tag: latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./images/jupyter/tensorflow-dbConnectors/Dockerfile
          push: true
          tags: kubespacedev/jupytertf-dbconn:${{ matrix.tag }}
          build-args: |
            IMAGE=${{ matrix.base }}
