name: Update Jupyter to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "jupyter/napptive/component310/**"
      - "jupyter/napptive/componentPROD/**"
      - "jupyter/napptive/componentPVC/**"
jobs:
  deploy:
    name: Upload new version to the catalog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          # - base: 'v3.9'
          #   tag: '39'
          # - base: 'v3.8'
          #   tag: '38'
          - base: 'latest'
            tag: 'prod'
          - base: 'storage'
            tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v6.0.2
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./jupyter/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Jupyter"
          tag: "${{ matrix.base }}"