name: Update Keycloak in to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "applications/keycloak/napptive/trialComponent/**"
      - "applications/keycloak/napptive/componentPROD/**"
      - "applications/keycloak/napptive/componentPVC/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          # - base: 'latest'
          #   tag: 'prod'
          # - base: 'storage'
          #   tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v6.0.2
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./applications/keycloak/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Keycloak"
          tag: "${{ matrix.base }}"