name: Nextcloud
on:
  push:
    branches:
      - 'main'
    paths:
      - "applications/nextcloud/napptive/trialComponent/**"
      - "applications/nextcloud/napptive/standardComponent/**"
      - "applications/nextcloud/napptive/pvcComponent/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          - base: 'standard'
            tag: 'standard'
          - base: 'storage'
            tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v6.0.2
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./applications/nextcloud/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Nextcloud"
          tag: "${{ matrix.base }}"