name: Update Redmine in to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "redmine/napptive/trialComponent/**"
      - "redmine/napptive/componentPROD/**"
      - "redmine/napptive/componentPVC/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          # - base: 'latest'
          #   tag: 'prod'
          # - base: 'storage'
          #   tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v4.2.0
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./redmine/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Redmine"
          tag: "${{ matrix.base }}"