name: Update Wiki.js in to Napptive Playground
on:
  push:
    branches:
      - 'main'
    paths:
      - "wikijs/napptive/trialComponent/**"
      - "wikijs/napptive/componentPROD/**"
      - "wikijs/napptive/componentPVC/**"
jobs:
  deploy:
    name: New version upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: 'trial'
            tag: 'trial'
          - base: 'latest'
            tag: 'prod'
          - base: 'storage'
            tag: 'pvc'
    steps:
      - uses: actions/checkout@v3
      - uses: napptive-actions/catalog-push-action@v6.0.2
        env:
          PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT }}
        with:
          applicationPath: ./wikijs/napptive/${{ matrix.tag }}Component/
          namespace: "kubespace"
          applicationName: "Wiki.js"
          tag: "${{ matrix.base }}"